"""
Server repository for database operations.
"""

from typing import Optional
from sqlmodel import Session, select
from datetime import datetime

from app.models.server import Server
from core.logger import setup_logger

logger = setup_logger(__name__)


class ServerRepository:
    """Repository for server database operations"""

    def get_by_id(self, db: Session, server_id: str) -> Optional[Server]:
        """Get server by ID"""
        statement = select(Server).where(Server.id == server_id)
        return db.exec(statement).first()

    def get_by_host(self, db: Session, host: str) -> Optional[Server]:
        """Get server by host"""
        statement = select(Server).where(Server.host == host)
        return db.exec(statement).first()

    def get_by_api_key(self, db: Session, api_key: str) -> Optional[Server]:
        """Get server by API key"""
        statement = select(Server).where(Server.api_key == api_key)
        return db.exec(statement).first()

    def get_all(self, db: Session, only_reachable: bool = False) -> list[Server]:
        """Get all servers"""
        statement = select(Server)

        if only_reachable:
            statement = statement.where(Server.is_reachable == True)

        return list(db.exec(statement).all())

    def create(self, db: Session, server: Server) -> Server:
        """Create a new server"""
        db.add(server)
        db.commit()
        db.refresh(server)
        logger.info(f"Server created: {server.name} ({server.host})")
        return server

    def update(self, db: Session, server: Server) -> Server:
        """Update server"""
        server.updated_at = datetime.utcnow()
        db.add(server)
        db.commit()
        db.refresh(server)
        logger.info(f"Server updated: {server.name} ({server.host})")
        return server

    def delete(self, db: Session, server: Server) -> bool:
        """Delete server"""
        try:
            db.delete(server)
            db.commit()
            logger.info(f"Server deleted: {server.name} ({server.host})")
            return True
        except Exception as e:
            logger.error(f"Error deleting server: {e}")
            db.rollback()
            return False

    def update_connectivity(
        self,
        db: Session,
        server: Server,
        is_reachable: bool,
        detected_services: Optional[str] = None,
        os_type: Optional[str] = None,
    ) -> Server:
        """Update server connectivity status"""
        server.is_reachable = is_reachable
        server.last_check = datetime.utcnow()

        if detected_services is not None:
            server.detected_services = detected_services

        if os_type is not None:
            server.os_type = os_type

        return self.update(db, server)

    def get_localhost(self, db: Session) -> Optional[Server]:
        """Get or create localhost server"""
        # Try to find existing localhost
        statement = select(Server).where(Server.is_local == True)
        localhost = db.exec(statement).first()

        if localhost:
            return localhost

        # Create localhost server
        # ID is auto-generated by model default_factory
        localhost = Server(
            name="localhost", host="127.0.0.1", description="Local machine", is_local=True, is_reachable=True
        )
        return self.create(db, localhost)


# Singleton instance
server_repository = ServerRepository()
